# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TrezorCrypto','0.0.9'
  pod 'BigInt'
  pod 'SwiftProtobuf'
  pod 'CryptoSwift','0.15.0'
  pod 'KeychainSwift'
  pod 'Moya', '~> 12.0.1'
  pod 'PromiseKit'
  
  # UILibrary
  pod 'MBProgressHUD'

  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
