# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TomoWalletCore' do

  pod 'TrezorCrypto','0.0.9', inhibit_warnings: true
  pod 'BigInt', inhibit_warnings: true
  pod 'SwiftProtobuf'
  pod 'CryptoSwift','0.15.0'
  pod 'KeychainSwift'
  pod 'Moya', '~> 12.0.1', inhibit_warnings: true
  pod 'PromiseKit'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TomoWalletCore

  target 'TomoWalletCoreTests' do
    inherit! :search_paths
    pod 'TrezorCrypto','0.0.9', inhibit_warnings: true
    pod 'BigInt', inhibit_warnings: true
    pod 'SwiftProtobuf'
    pod 'CryptoSwift','0.15.0'
    pod 'KeychainSwift'
    pod 'Moya', '~> 12.0.1', inhibit_warnings: true
    pod 'PromiseKit'
    # Pods for testing
  end

end
